import nbtlib
from ..world.define import BlockStates, Dimension, Range

CURRENT_BLOCK_VERSION = 18153728

EMPTY_COMPOUND = nbtlib.tag.Compound()
EMPTY_BLOCK_STATES = EMPTY_COMPOUND

DIMENSION_ID_OVERWORLD = 0
DIMENSION_ID_NETHER = 1
DIMENSION_ID_END = 2

DIMENSION_OVERWORLD = Dimension(DIMENSION_ID_OVERWORLD)
DIMENSION_NETHER = Dimension(DIMENSION_ID_NETHER)
DIMENSION_END = Dimension(DIMENSION_ID_END)

RANGE_OVERWORLD = DIMENSION_OVERWORLD.range()
RANGE_NETHER = DIMENSION_NETHER.range()
RANGE_END = DIMENSION_END.range()
RANGE_INVALID = Range(0, -1)

AIR_BLOCK_STATES = BlockStates("minecraft:air")
INVALID_BLOCK_RUNTIME_ID = (1 << 32) - 1
