name: Build C Depends



on:
  push:
    branches: [ main ]
    paths:
      - "version"
  workflow_dispatch: {}



jobs:
  Builder:
    runs-on: macos-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.24'

    - name: Install Dependencies
      run: |
        brew install mingw-w64
        brew install messense/macos-cross-toolchains/x86_64-unknown-linux-gnu
        brew install messense/macos-cross-toolchains/aarch64-unknown-linux-gnu
        brew install make

    - name: Build and Move Files
      run: |
        cd c_api
        make all
        rm -rf dynamic_libs/*.h
        rm -rf ../python/package/dynamic_libs
        mv dynamic_libs ../python/package

    - name: Submit Changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'Build C depends and submit'